### ISSUE TITLE
dev启动能否改进下

### ISSUE THREAD

**Issue by zwmmm** [coocssweb/react-ssr#1]
按照这个demo,需要启动三步才能使用,看了你的源码是先生成模板,然后用dev-server作为静态资源服务器
,最后才启动后端服务

我自己尝试了下,将dev-server整合进了node服务器, 但是会造成 index.html 被dev-server拦截,而没有next到路由上,不知道有没有办法解决,还有dev-server有没有一种钩子,可以在编译结束之后执行生成模板的操作

**Comment by coocssweb** [comment]
@zwmmm 

这个其实挺好解决的，就是在/package.json 文件的script属性下，把多个需要运行脚本命令命令拼一下就可以啦。这样就不用修改webpack.js的任何操作。让webpack做单纯的构建、和资源服务器的启动
比如(原来的脚本是这样的)：

> "scripts": {
>    "start": "webpack-dev-server --config build/webpack.dev.config.js --open --hot",
>    "server:dev": "export NODE_ENV=development && nodemon ./server/index.js",
>    "server": "export NODE_ENV=production && nohup node ./server/index.js > nohup.log 2>&1 &",
>    "build:local": "webpack --mode production --config build/webpack.local.config.js --progress --hide-modules",
>    "build:test": "webpack --mode production --config build/webpack.test.config.js --progress --hide-modules",
>    "build": "webpack --mode production --config build/webpack.production.config.js --progress --hide-modules"
  }

你可以改成这样： 

> "scripts": {
>    "start": "webpack-dev-server --config build/webpack.dev.config.js --open --hot",
>    "server:dev": "export NODE_ENV=development && nodemon ./server/index.js",
>    "server": "export NODE_ENV=production && nohup node ./server/index.js > nohup.log 2>&1 &",
>    "build:local": "webpack --mode production --config build/webpack.local.config.js --progress --hide-modules",
>    "build:test": "webpack --mode production --config build/webpack.test.config.js --progress --hide-modules",
>    "build": "webpack --mode production --config build/webpack.production.config.js --progress --hide-modules",
>    "dev": "npm run build:local && npm start && npm server:dev"
  }

这样，就可以只通过运行 
`npm run dev`
开启开发

**Comment by zwmmm** [comment]
这确实也是一种办法 最近看了你的代码自己撸了一套ssr 想着写篇文章总结下, 你看同不同意 毕竟大部分思路都是借鉴的你的

**Comment by coocssweb** [comment]
@zwmmm 当然可以，你总结整理出来就是你自己的思维啦，这个无所谓哈。
如果你觉得，这个demo还可以，文章可以加上git仓库链接哈，不加也无所谓哈。

**Comment by coocssweb** [comment]
> 这确实也是一种办法 最近看了你的代码自己撸了一套ssr 想着写篇文章总结下, 你看同不同意 毕竟大部分思路都是借鉴的你的

https://juejin.im/post/5c90b4115188252d9559136c
你好，这篇文章是你写的吗？
文章上面你提供您的git仓库，我看了下，连webpack工程化的代码都是我这个仓库的。而且，你没有备注出处，这严重影响了我的原创性。
这套方案并不是你的思维，希望你能尊重下原创。
